name: CI/CD Workflow

# 1. Agora ele roda tanto na Main quanto em Pull Requests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies with poetry
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

      # 2. ESSA É A MÁGICA: Comando que controi e publica a documentação
      - name: Deploy MkDocs Documentation
        run: poetry run mkdocs gh-deploy --force